AllCops:
  TargetRubyVersion: 2.6

Metrics/AbcSize:
  Exclude:
    - bin/**/*

Metrics/CyclomaticComplexity:
  Exclude:
    - bin/**/*

Metrics/LineLength:
  Max: 125
  Exclude:
    - bin/**/*

Metrics/MethodLength:
  Exclude:
    - bin/**/*

Metrics/PerceivedComplexity:
  Exclude:
    - bin/**/*

Style/IfUnlessModifier:
  Exclude:
    - bin/**/*
